---
title: "Strings and factors"
author: "Zachary Katz"
date: "10/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Strings and vectors

```{r}
string_vec = c("my", "name", "is", "jeff")

# Returns TRUE for last one because case sensitive
str_detect(string_vec, "jeff")

# Returns FALSE for last one because case sensitive
str_detect(string_vec, "Jeff")

str_replace(string_vec, "jeff", "zak")

# Replace with empty space
str_replace(string_vec, "e", "")
```

Note that strings are case-sensitive!

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
)

str_detect(string_vec, "i think")

# Use ^ to represent beginning of line
# Only shows when it starts the phrase
str_detect(string_vec, "^i think")

# For end of phrase instead of beginning
str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
)

str_detect(string_vec, "bush")

str_detect(string_vec, "Bush")

str_detect(string_vec, "[Bb]ush")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

# Which phrases start with 1st, 2nd, 3rd etc?
str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

# Want to find 7, then anything, then 11
str_detect(string_vec, "7.11")
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

# Want to search for something that actually has a square open bracket
# Extra backslash because \ is itself a special chararacter
str_detect(string_vec, "\\[")
```

## Why factors are weird

```{r}
factor_vec = factor(c("male", "male", "female", "female"))
factor_vec

# Converts females to 1, males to 2
as.numeric(factor_vec)

factor_vec = fct_relevel(factor_vec, "male")
factor_vec

# Converts males to 1, females to 2
as.numeric(factor_vec)
```

See? Some weird stuff happens in background if you don't keep track of what's going on with your labels and factor level orderings.

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) %>% 
  html_table() %>% 
  first() %>%
  slice(-1)

table_marj
```

```{r}
table_marj %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) %>% 
  # In this case, separate 11 characters from end of phrase
  separate(age_year, into = c("age", "year"), -11)

marj_df = table_marj %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) %>% 
  # In this case, separate at open parenthesis
  separate(age_year, into = c("age", "year"), "\\(") %>% 
  # Get rid of some extraneous characters and make sure percent is numeric
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)
  ) %>% 
  # Do NOT keep anything in state var that matches these conditions (i.e. regional and national totals)
  filter(!State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West"))
```

Now, can do fun data frame stuff.

```{r}
marj_df %>% 
  filter(age == "12-17") %>% 
  mutate(
    State = fct_reorder(State, percent)
  ) %>% 
  ggplot(aes(x = State, y = percent, color = year)) + 
  geom_point() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Note that neither color is in order from least to greatest; uses the median.
